### ISSUE TITLE
Example in Readme.md has errors

### ISSUE THREAD

**Issue by WaterJuice** [amirhosseinalikhahm/BIP32-Ed25519#1]
There are two issues with your example in Readme.md.
First the the line "memset(string, 0,sizeof(string));" Is accessing unassigned memory, and will at best do nothing harmful, more likely crash the program (in the example where I compiled for Windows it crashed). There is no need for this line at all, as string is a pointer which you then assign to a string constant. 

The second issue is the printing of the output. You are printing byte by byte using %x. This will print only 1 character where the value of the byte is less than 0x10. So if the byte is 0x07 it will simply print "7". Which is why your final output seems to be dropping zeros.
To fix this you need to force printf to always print 2 characters. Change "%x" to "%2.2x" and you will get the correct printing.

**Comment by amirhosseinalikhahm** [comment]
thank you ... I modified it ...
